### ISSUE TITLE
Missing parenthesis around ternary operation in Javascript

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct_compiler#52] opened 2016-12-23 21:22 UTC
This
`b1 * (1 == 0 ? 128 : 1)`
generates
`(this.b1 * 1 == 0 ? 128 : 1);`
instead of
`(this.b1 * (1 == 0 ? 128 : 1));`

**Comment by GreyCat** [comment] 2016-12-23 22:50
Probably it's duplicate of https://github.com/kaitai-io/kaitai_struct_compiler/issues/39 ?

**Comment by GreyCat** [comment] 2017-08-23 12:34
I've just checked, this particular bug seems to be solved, now it generates:

```javascript
      this._m_foo = (this.b1 * (1 == 0 ? 128 : 1));
```

Thus I'm closing this bug, and probably all other activities on this elusive operator parenthesis / priority question should go into https://github.com/kaitai-io/kaitai_struct/issues/69.

**Closed by GreyCat** 2017-08-23 12:34 UTC
Labels: bug
